on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The name of the protected branch to delete.'
        required: true
        type: string

name: Delete Protected Branch
run-name: Delete branch ${{ inputs.branch }}

jobs:
  delete-protected-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete protected branch
        uses: BeamMoney/packaged-actions/.github/actions/delete-protected-branch@main
        with:
          branch: ${{ inputs.branch }}
          github-app-id: ${{ secrets.GH_ACTIONS_CONTRIBUTOR_ID }}
          github-app-key: ${{ secrets.GH_ACTIONS_CONTRIBUTOR_PRIVATE_KEY }}